# Generated by Django 6.0.2 on 2026-02-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('registrationLocked', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(blank=True, related_name='event_admins', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('referees', models.ManyToManyField(blank=True, related_name='event_referees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('scheduledStartTime', models.DateTimeField()),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ORCA.event')),
            ],
        ),
        migrations.CreateModel(
            name='MatchBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('matchCount', models.IntegerField()),
                ('timeBetweenMatches', models.IntegerField(help_text='Time between matches in minutes')),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORCA.event')),
            ],
            options={
                'ordering': ['order', 'startTime'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artifacts', models.IntegerField()),
                ('minorFouls', models.IntegerField()),
                ('majorFouls', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ORCA.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='blueScoreSheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blue_scoreSheet', to='ORCA.scoresheet'),
        ),
        migrations.AddField(
            model_name='match',
            name='redScoreSheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='red_scoreSheet', to='ORCA.scoresheet'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='blue1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_blue1', to='ORCA.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='blue2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_blue2', to='ORCA.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_red1', to='ORCA.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='red2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_red2', to='ORCA.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='event_teams', to='ORCA.team'),
        ),
    ]
