# Generated by Django 6.0.2 on 2026-03-01 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORCA', '0002_alter_match_bluescoresheet_alter_match_redscoresheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='blueScoreSheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_scoreSheet', to='ORCA.scoresheet'),
        ),
        migrations.AlterField(
            model_name='match',
            name='redScoreSheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_scoreSheet', to='ORCA.scoresheet'),
        ),
    ]
