# Generated by Django 6.0.2 on 2026-03-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORCA', '0003_alter_match_bluescoresheet_alter_match_redscoresheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='team1endgame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='team2endgame',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
